
post_install() {
  script_path=/tmp/get_install_dir_for_pyne_data.py
  echo 'from pyne.api import nuc_data' > $script_path
  echo 'print nuc_data' >> $script_path
  install_path=`python2 $script_path`
  rm $script_path
  nuc_data_make -o $install_path
}

pre_remove() {
  script_path=/tmp/get_install_dir_for_pyne_data.py
  echo 'from pyne.api import nuc_data' > $script_path
  echo 'print nuc_data' >> $script_path
  install_path=`python2 $script_path`
  rm $script_path
  rm $install_path
}
